services:
  - type: web
    name: tradeiq-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: WEB_ORIGIN
        sync: false
      - key: MOBILE_ORIGIN
        value: "*"
